baseURL: https://armno.in.th/
disablePathToLower: true
languageCode: th
title: Frontend Developer at BUZZWOO! Asia, Chiang Mai, Thailand. <3 Web Platform. Blogs about web and frontend toolings.
thumbnail: https://armno.in.th/img/cover-blog-stuttgart.jpg
theme: armno
permalinks:
  post: /:year/:month/:day/:slug/
pygmentsStyle: "murphy"
pygmentsCodefences: true
ignoreFiles:
  - "_drafts"
blackfriday:
  extensionsmask:
    - noIntraEmphasis
