baseURL: https://armno.in.th/
disablePathToLower: true
languageCode: th
title: Armno P. - Frontend Developer at BUZZWOO! Asia, Chiang Mai, Thailand.
params:
  thumbnail: https://armno.in.th/img/blog-social-media-cover.png
theme: lazy
paginate: 12
permalinks:
  post: /:year/:month/:day/:slug/
pygmentsStyle: 'friendly'
pygmentsCodefences: true
ignoreFiles:
  - '_drafts'
blackfriday:
  extensionsmask:
    - noIntraEmphasis
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: date
      weight: 10
enableGitInfo: true
enableRobotsTXT: true
timeout: 30000
markup:
  goldmark:
    renderer:
      unsafe: true
