version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to the registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker Image
          command: docker build --tag armno/blog:$CIRCLE_BRANCH .
      - run:
          name: Push to the registry
          command: docker push armno/blog:$CIRCLE_BRANCH

workflows:
  version: 2
  just-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
